version: '3'

services:
  web:
    build: .
    volumes:
      - static_volume:/app/static
    env_file:
      - ./app/config/.env
    entrypoint: [ "sh", "/app/entrypoint.sh" ]
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/config/.env

  nginx:
    image: nginx:1.18
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
    depends_on:
      - web
    ports:
      - "80:80"
      - "8000:80"

volumes:
  postgres_data:
  static_volume: